#!usr/bin/env bash
export VENV="$PWD/geru_challenge/env"
export DB="$PWD/geru_challenge/geru_db.db"
export GERU_DEV_INI="$PWD/geru_challenge/development.ini"
alias geru_stop='for pid in $(pgrep -lfa geru_challenge | cut -d" " -f1); do kill -9 $pid; done'
alias geru_start='geru_stop; $VENV/bin/pserve $GERU_DEV_INI --reload &>/dev/null & disown'
alias geru_restart='geru_stop; geru_start'
